= Szkolenie Kubernetes w praktyce
:author: Juliusz Marciniak
:imagesdir: ./images
:toc:
:toclevels: 4
:toc-title: Spis treści

<<<

== Opis

Szkolenie Kubernetes w praktyce obejmuje naukę i praktyczne doświadczenie związane z zarządzaniem kontenerami. Uczestnicy zdobędą umiejętności w zakresie instalacji, konfiguracji i utrzymania klastra Kubernetes, co obejmuje zarządzanie zasobami, skalowalność i dostępność. W trakcie szkolenia praktycznego uczestnicy bedą pracować nad rzeczywistymi przypadkami użycia, implementować aplikacje w kontenerach i nauczą się jak skutecznie monitorować oraz debugować środowisko. Ponadto szkolenie obejmuje tematy związane z bezpieczeństwem, takie jak zarządzanie dostępem, autentykacja i szyfrowanie. Kurs ten umożliwi uczestnikom zrozumienie pełnego ekosystemu Kubernetes i przygotuje ich do efektywnego wdrażania i utrzymania aplikacji w kontenerach w środowisku produkcyjnym.

== O trenerze

Imię i nazwisko: Juliusz Marciniak

Zawód: Programista, DevOps, TechLead

Doświadczenie: 10 lat

Technologie:

* Java, Spring
* Jenkins, GitLab, Nexus
* Docker, Kubernetes

Jestem programistą Java z 10-letnim stażem. W codziennej pracy zajmuję się tematami cloudowymi i Kubernetesowymi. Oprócz tego doglądam architektury aplikacji w swoich projektach. Jestem entuzjastą nowych rozwiązań i technologii. Zwracam dużą uwagę, by rzeczy wdrażane przeze mnie były przemyślane i spójne. Czasami też programuję... i rekrutuję.

== Agenda
. Docker
. Architektura Kubernetes
. Podstawy konfiguracji
. Uwierzytelnianie oraz autoryzacja
. Sieci
. Storage
. Dodatkowe funkcjonalności
. Logowanie oraz Monitoring
. Bezpieczeństwo
. Dystrybucje oraz użyteczne narzędzia
. Helm jako natywny menedżer pakietów aplikacji w Kubernetes

== Zasady
* Staramy się nie spóźniać
* Telefon odbieramy poza salą
* Jesteśmy aktywni
* Jeśli utknęliśmy na problemie podczas realizacji zadań — natychmiast informujemy
* Nie śmiejemy się z innych i nie krytykujemy pomysłów innych
* Każdy ma prawo do wyrażania swojej opinii
* Przerwa na kawę co 1-1,5h
* Przerwa obiadowa o 13:00

<<<

include::theory/README.adoc[leveloffset=1]

<<<

include::docker/README.adoc[leveloffset=1]

<<<

include::kubernetes/README.adoc[leveloffset=1]
